version: '3'
services:
    mongo-server:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db
        networks: 
            - mongo-compose-network
    mongo-express:
        image: mongo-express
        depends_on:
            - mongo-server
        ports:
            - 9090:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongo-server
        networks: 
            - mongo-compose-network
    my-app:
        image: npdangkhoa/my-app:1.2
        depends_on:
            - mongo-server
            - mongo-express
        networks:
            - mongo-compose-network
        ports:
            - 3000:3000
volumes: 
    mongo-data:
        driver: local
networks:
    mongo-compose-network:
        driver: bridge
